### ISSUE TITLE
Remove lint:style from package.json if style support is false

### ISSUE THREAD

**Issue by aravindarr** [yohangz/packer-cli#6]
Remove lint:style from scripts if style support (Question 8) is set to false.

**Comment by aravindarr** [comment]
Issue was still there. to reproduce follow these steps:
Generate project with style false -> set rest to default configurations

Seems `package.json` didn't remove the lint:style from the script object. and once after success project generation user can run `packer lint --style` command and will leads to unhandled error. this will also cause to fail the packer lint script command.

**Comment by yohangz** [comment]
Fix applied
